# Generated by Django 5.0.6 on 2024-09-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pub_date", models.DateField(verbose_name="published_date")),
                ("income", models.DecimalField(decimal_places=4, max_digits=16)),
                ("desc", models.CharField(max_length=255)),
            ],
        ),
    ]
