# Generated by Django 5.1.1 on 2024-10-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(verbose_name='published_date')),
                ('spent', models.DecimalField(decimal_places=4, max_digits=16)),
                ('desc', models.CharField(max_length=255)),
            ],
        ),
    ]
